tags = [
    'existential',
    'philosophical',
    'comical',
    'whimsical',
    'serious',
    'nostalgic',
    'romantic',
    'religious',
    'logophilic',
    'melancholic',
    'adventurous',
    'reflective',
    'satirical',
    'nature',
    'surreal'
]