tags = [
    'adventurous',
    'comical',
    'educational',
    'existential',
    'logophile',
    'melancholic',
    'nature',
    'nostalgic',
    'philosophical',
    'reflective',
    'religious',
    'romantic',
    'satirical',
    'serious',
    'surreal',
    'whimsical'
]